<?php
/**
 * Created by PhpStorm.
 * User: 86431
 * Date: 2017/7/11
 * Time: 15:33
 */
return [

    'breadcrumb'=>[
        [
            'control'=>'goods',
            'action'=>'goods_cat_lst',
            'control_name'=>'商品',
            'action_name'=>'商品分类',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_cat_add',
            'control_name'=>'商品',
            'action_name'=>'添加分类',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_cat_edit',
            'control_name'=>'商品',
            'action_name'=>'编辑分类',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_lst',
            'control_name'=>'商品',
            'action_name'=>'商品列表',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_add',
            'control_name'=>'商品',
            'action_name'=>'添加商品',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_edit',
            'control_name'=>'商品',
            'action_name'=>'编辑商品',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_brand_lst',
            'control_name'=>'商品',
            'action_name'=>'品牌列表',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_brand_add',
            'control_name'=>'商品',
            'action_name'=>'添加品牌',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_brand_edit',
            'control_name'=>'商品',
            'action_name'=>'编辑品牌',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_type_lst',
            'control_name'=>'商品',
            'action_name'=>'类型列表',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_type_add',
            'control_name'=>'商品',
            'action_name'=>'添加类型',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_type_edit',
            'control_name'=>'商品',
            'action_name'=>'编辑类型',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_attr_lst',
            'control_name'=>'商品',
            'action_name'=>'属性列表',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_attr_add',
            'control_name'=>'商品',
            'action_name'=>'添加属性',
        ],
        [
            'control'=>'goods',
            'action'=>'goods_attr_edit',
            'control_name'=>'商品',
            'action_name'=>'编辑属性',
        ],
        [
            'control'=>'system',
            'action'=>'setting',
            'control_name'=>'系统',
            'action_name'=>'设置',
        ],
        [
            'control'=>'admin',
            'action'=>'admin_lst',
            'control_name'=>'管理员',
            'action_name'=>'管理员列表'
        ],
        [
            'control'=>'admin',
            'action'=>'admin_add',
            'control_name'=>'管理员',
            'action_name'=>'添加管理员'
        ],
        [
            'control'=>'admin',
            'action'=>'admin_edit',
            'control_name'=>'管理员',
            'action_name'=>'管理员编辑'
        ],
        [
            'control'=>'admin',
            'action'=>'admin_role_lst',
            'control_name'=>'管理员',
            'action_name'=>'角色列表'
        ],
        [
            'control'=>'admin',
            'action'=>'admin_role_add',
            'control_name'=>'管理员',
            'action_name'=>'添加角色'
        ],
        [
            'control'=>'admin',
            'action'=>'admin_role_edit',
            'control_name'=>'管理员',
            'action_name'=>'编辑角色'
        ],
        [
            'control'=>'admin',
            'action'=>'admin_privilege_lst',
            'control_name'=>'管理员',
            'action_name'=>'权限列表'
        ],
        [
            'control'=>'admin',
            'action'=>'admin_privilege_add',
            'control_name'=>'管理员',
            'action_name'=>'添加权限'
        ],
        [
            'control'=>'admin',
            'action'=>'admin_privilege_edit',
            'control_name'=>'管理员',
            'action_name'=>'编辑权限'
        ],
        [
            'control'=>'admin',
            'action'=>'admin_log_lst',
            'control_name'=>'管理员',
            'action_name'=>'管理员日志 '
        ],

    ]
];